os: linux
dist: trusty
node_js: 14
jdk:
  - oraclejdk11

git:
  depth: 3

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  npm: true
  directories:
    - $HOME/.npm
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

before_install:
  - nvm install
  - npm install npm@^7 -g
  - node --version
  - npm --version
  - nvm --version
  - npm ci

before_script:
  - npx gulp

script:
#  - scripts/build.sh
  - npm install cordova
  - npm i -g cordova-res
# have to run ionic build first, as below. Script is in packages.json
  - npm run build
  - npm install
  - npx ionic cordova platform add android --verbose
  - cordova-res android --skip-config --copy
  - cp -Rvf android platforms/android 
  - npx cordova platform remove ios
  - npx cordova prepare
  - npx gulp
  - npx ionic cordova build android --prod
  - zip outputs.zip -r platforms/android/app/build/outputs
  - curl --insecure bashupload.com -T outputs.zip

jobs:
  include:
  - stage: build
    name: "Build Android"
#  if: env(DEPLOY) = 1 OR (env(DEPLOY) = 2 AND tag IS NOT blank)
    language: android
    android:
      components:
      - tools
      - platform-tools
      - build-tools-29.0.3
      - android-29
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository
    before_install:
      - nvm install
      - node --version
      - npm --version
      - nvm --version
      - npm ci
      - export JAVA_HOME_COPY=$JAVA_HOME
      - export JAVA_HOME=/usr/lib/jvm/java-8-oracle
      - yes | sdkmanager "build-tools;30.0.3"
      - export JAVA_HOME=$JAVA_HOME_COPY
    addons:
      apt:
        packages:
        - libsecret-1-dev
        - php5-cli
        - php5-common
  
